sudo: false
language: python
cache: pip

python:
  - "2.7"
  - "3.5"
  - "3.6"

script:
  - flake8
  - py.test --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: $PyPiLogin
  password: $PyPiPassword
  on:
    tags: true
